

/*
1)What is the total revenue generated by the stores across all orders?
*/

select 
Round(Sum(Quantity*list_price*(1-discount)),0) as total_price
from
order_items;

/*
2)Show total sales for each month in 2016
*/
SELECT
EXTRACT(MONTH FROM o.order_date) AS order_month,
Round(SUM(oi.quantity * oi.list_price * (1 - oi.discount)),0) AS monthly_revenue
FROM
orders AS o
JOIN
order_items AS oi ON o.order_id = oi.order_id
WHERE
EXTRACT(YEAR FROM o.order_date) = 2016
GROUP BY
order_month
ORDER BY
order_month;

/*
3)Which  5 product generated the highest revenue
*/

SELECT
p.product_name,
Round(SUM(oi.quantity * oi.list_price * (1 - oi.discount)),2) AS total_revenue
FROM
products AS p
JOIN order_items AS oi ON p.product_id = oi.product_id
GROUP BY
p.product_name
ORDER BY
total_revenue DESC
LIMIT 5;

/*
4)Who are the top 10 customers by total spend?
*/

Select
c.first_name,c.last_name,
Round(SUM(oi.quantity * oi.list_price * (1 - oi.discount)),2) AS total_spend
from
customers c
Join
orders o
On
c.customer_id=o.customer_id
Join
order_items oi 
ON
o.order_id=oi.order_id
Group by
c.customer_id,
c.first_name,
c.last_name
order by total_spend desc
Limit 10;

/*
5)What is the average order value per customer?
*/

WITH OrderValues AS (SELECT
o.customer_id,
o.order_id,
SUM(oi.quantity * oi.list_price * (1 - oi.discount)) AS total_order_value
FROM
orders AS o
JOIN
order_items AS oi ON o.order_id = oi.order_id
GROUP BY
o.customer_id,
o.order_id)

SELECT
c.first_name,
c.last_name,
Round(AVG(ov.total_order_value),2) AS average_order_value
FROM
Customers AS c
JOIN
OrderValues AS ov ON c.customer_id = ov.customer_id
GROUP BY
c.first_name,
c.last_name
ORDER BY
average_order_value DESC;


/*
6)How many customers placed more than one order?
*/

Use project;


Select count(customer_id) as  order_placed_more_than_onced from(
Select
customer_id
from 
orders
group by customer_id
Having
Count(order_id)>1)t
; 

/*
7)Compare revenue across different locations
*/

Select 
o.store_id,s.store_name,s.street,s.city,Round(SUM(ot.quantity * ot.list_price * (1 - ot.discount)),2) as total_revenue_by_locations from 
stores s
join
Orders o
ON s.store_id=o.store_id
Join 
Order_items ot
ON
o.order_id=ot.order_id
Group by
o.store_id,s.store_name,s.street,s.city;

/*
8)Which product categories contribute the most revenue?
*/

SELECT
c.category_name,
ROUND(SUM(oi.quantity * oi.list_price * (1 - oi.discount)), 2) AS total_revenue
FROM
categories c
JOIN
products p ON c.category_id = p.category_id
JOIN
order_items oi ON p.product_id = oi.product_id
GROUP BY
c.category_name
ORDER BY
total_revenue DESC;

/*
9)Which products had the least sales (by quantity)?
*/
SELECT
p.product_name,
SUM(oi.quantity) AS total_quantity_sold
FROM
products AS p
JOIN
order_items AS oi ON p.product_id = oi.product_id
GROUP BY
p.product_name
ORDER BY
total_quantity_sold ASC;

/*
10)Who are the top-performing salespeople by sales value?
*/
SELECT
s.first_name,
s.last_name,
Round(SUM(oi.quantity * oi.list_price * (1 - oi.discount)),0) AS total_sales
FROM
staffs AS s
JOIN
orders AS o ON s.staff_id = o.staff_id
JOIN
order_items AS oi ON o.order_id = oi.order_id
GROUP BY
s.first_name,
s.last_name
ORDER BY
total_sales DESC
LIMIT 10;

